### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by boo1ean** [makeusabrew/decking-example#3]
```
root at drone-ci ~/decking-example # docker -v
Docker version 1.2.0, build fa7b24f

root at drone-ci ~/decking-example # decking create dev
Using overrides from group 'dev'

redis.dev    creating...
mongodb.dev  ...
redis.dev    creating... ✔
mongodb.dev  creating... ✔
api.dev      creating...
admin.dev    ...
web.dev      ...
Error: Command failed: Unable to find image 'decking/example-api' locally
Pulling repository decking/example-api
2014/10/13 14:24:15 Error: image decking/example-api not found

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by makeusabrew** [comment]
Should be fixed now thanks to @mrflip's documentational efforts.
